### ISSUE TITLE
Train error when using pretrained model

### ISSUE THREAD

**Issue by trikim** [facebookresearch/multigrain#4]
Model state loaded from experiments/joint_3B_0.5/checkpoint_2.pth
Traceback (most recent call last):
  File "scripts/train.py", line 254, in <module>
    run(args)
 File "scripts/train.py", line 158, in run
    begin_epoch, loaded_extra = checkpoints.resume(model, optimizers, metrics_history, args.resume_epoch, args.resume_from)
  File "/tmp/multigrain/multigrain/utils/checkpoint.py", line 114, in resume
    optimizer.load_state_dict('optimizer_state')
  File "/tmp/multigrain/multigrain/modules/multioptim.py", line 28, in load_state_dict
    for k, v in D.items():
AttributeError: 'str' object has no attribute 'items'

I think this line https://github.com/facebookresearch/multigrain/blob/a8e5bbfd5caeeaeb61631b63659a5381d1d3aed9/multigrain/utils/checkpoint.py#L114  should changed to :
`optimizer.load_state_dict(checkpoint['optimizer_state'])`
Is it right?

**Comment by bermanmaxim** [comment]
Indeeed, thank you!
